Repository akshitdesai/OSMDashboard-Winter-2024-SOEN-6431, pull requests merged in 2024-02, with the labels that each got.

#18 Update PreferencesUtils.java
  src/main/java/de/storchp/opentracks/osmplugin/utils/PreferencesUtils.java
Labels: Technical Debt

#21 Amini merge if techdebt
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/TrackPoint.java
Labels: Technical Debt

#23 add default case in switch in StyleCreator file
  src/main/java/de/storchp/opentracks/osmplugin/maps/StyleColorCreator.java
Labels: Technical Debt, Group 17

#29 simplify inheritance
  src/main/java/de/storchp/opentracks/osmplugin/MainActivity.java
Labels: Technical Debt, Group 17

#31 render modifier according to java language specification
  src/main/java/de/storchp/opentracks/osmplugin/DownloadActivity.java
Labels: Technical Debt, Group 17

#33 remove parenthesis around view parameter in lambda function
  src/main/java/de/storchp/opentracks/osmplugin/DownloadActivity.java
Labels: Group 17
